name: CI

on:
  push:
    branches: [ master, decaffeinate ]
  pull_request:
    branches: [ master, decaffeinate ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Releases https://github.com/nodejs/release#release-schedule
        node-version:
          - 18.x # Maintenance
          - 20.x # LTS
          - 22.x # Current

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
